language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706_Maximova_All_Lab
  - make -j
  - ./VectorTest/VectorTest
notifications:
  email: false
