language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706_Maximova_All_Lab
  - make -j
  - ./VectorTest/VectorTest
  - ./MatrixTest/MatrixTest
  - ./StackTest/StackTeTest
  - ./QueueTest/QueueTest
  - ./ListTest/ListTest
  - ./ArrListTest/ArrListTest
notifications:
  email: false
