language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706_MaximovaIrina_All_Lab
  - make -j
  - ./Vector/Vector
notifications:
  email: false
